Concepts:
  Liver failure:
    cui: 59927004
    ontologies: SNOMED-CT
  Paracetamol:
    cui: 90332006
    ontologies: FDB

CDA:
  Problems:
    # whether problem is an active concern to clinician
    statusCode: active
    # time when the problem stop become a concern to clinician -  there will always be a low (implicit)
    actEffectiveTimeHigh: false
    # problem onset - can be a date in the past
    observationEffectiveTimeLow: '20200504'
    # problem resolve date
    observationEffectiveTimeHigh: '20210904'

  Medications:
    effectiveTimePeriod: true
    effectiveTimeLow: true
    doseQuantity: true
    routeCode: true
    SIG: true

  Allergy:
    statusCode: active
    effectiveTimeLow: true
    reactionObservation: true

Model:
  modelId: 0