# file generated by setuptools_scm
# don't change, don't track in version control
__version__ = version = '0.1.dev170+gb7a0a11.d20230113'
__version_tuple__ = version_tuple = (0, 1, 'dev170', 'gb7a0a11.d20230113')